### ISSUE TITLE
Installing dependencies on gpu2

### ISSUE THREAD

**Issue by juliagusak** [yandexdataschool/Practical_RL#29]
Could someone with sudo rights  install  ffmpeg and avconv on Shad' gpu, please?

**Comment by justheuristic** [comment]
Done. Did it help?

**Comment by juliagusak** [comment]
Yes, thank you!

**Comment by juliagusak** [comment]
Could you  install ppaquette-gym-doom on Shad's gpu2, please?

 'pip install ppaquette-gym-doom'  didn't work for me, because I can't install all required dependicies without  sudo rights.

I also tried  'pip install gym-pull' , but after
import gym
import gym_pull
gym_pull.pull('github.com/ppaquette/gym-doom')       
env = gym.make('ppaquette/DoomBasic-v0')

an error 'No registered env with id: ppaquette/DoomBasic-v0' occured

**Comment by justheuristic** [comment]
All the dependencies are installed, you can install doom under user

**Comment by juliagusak** [comment]
I still get an error trying to install doom with 'pip install ppaquette-gym-doom' (what am I doing wrong?):

Collecting ppaquette-gym-doom
Requirement already satisfied: gym>=0.8.0 in /anaconda2/lib/python2.7/site-packages (from ppaquette-gym-doom)
Collecting doom-py>=0.0.11 (from ppaquette-gym-doom)
  Using cached doom-py-0.0.15.tar.gz
Requirement already satisfied: six in /anaconda2/lib/python2.7/site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Requirement already satisfied: requests>=2.0 in /anaconda2/lib/python2.7/site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Requirement already satisfied: pyglet>=1.2.0 in /anaconda2/lib/python2.7/site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Requirement already satisfied: numpy>=1.10.4 in /anaconda2/lib/python2.7/site-packages (from gym>=0.8.0->ppaquette-gym-doom)
Building wheels for collected packages: doom-py
  Running setup.py bdist_wheel for doom-py ... error
  Complete output from command /anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ivIkqp/doom-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpQgXoUzpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Check for working C compiler: /anaconda2/bin/cc
  -- Check for working C compiler: /anaconda2/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /anaconda2/bin/c++
  -- Check for working CXX compiler: /anaconda2/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
    Unable to find the requested Boost libraries.
  
    Boost version: 1.61.0
  
    Boost include path: /usr/include
  
    Could not find the following Boost libraries:
  
            boost_filesystem
            boost_thread
            boost_system
            boost_date_time
            boost_chrono
            boost_regex
            boost_iostreams
  
    Some (but not all) of the required Boost libraries were found.  You may
    need to install these additional Boost libraries.  Alternatively, set
    BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
    to the location of Boost.
  Call Stack (most recent call first):
    CMakeLists.txt:54 (find_package)
  
  
  -- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
  -- Found JPEG: /anaconda2/lib/libjpeg.so
  -- Found ZLIB: /anaconda2/lib/libz.so (found version "1.2.8")
  -- Could NOT find GME (missing:  GME_LIBRARIES GME_INCLUDE_DIR)
  -- Using system zlib
  -- Using system jpeg library
  -- Using internal bzip2 library
  -- Using internal gme library
  -- Performing Test HAVE_NO_ARRAY_BOUNDS
  -- Performing Test HAVE_NO_ARRAY_BOUNDS - Success
  -- Performing Test __LIBGME_TEST_VISIBILITY
  -- Performing Test __LIBGME_TEST_VISIBILITY - Success
  -- Looking for strdup
  -- Looking for strdup - found
  -- Looking for strndup
  -- Looking for strndup - found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of char
  -- Check size of char - done
  -- Check size of short
  -- Check size of short - done
  -- Check size of int
  -- Check size of int - done
  -- Check size of long
  -- Check size of long - done
  -- /anaconda2/include
  -- /tmp/pip-build-ivIkqp/doom-py/doom_py/src/vizdoom/bzip2
  -- /tmp/pip-build-ivIkqp/doom-py/doom_py/src/vizdoom/lzma/C
  -- Looking for itoa
  -- Looking for itoa - not found
  -- Performing Test DUMB_CAN_USE_SSE
  -- Performing Test DUMB_CAN_USE_SSE - Success
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
  -- Checking for module 'gtk+-2.0'
  --   No package 'gtk+-2.0' found
  CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find SDL2 (missing: SDL2_LIBRARY)
  Call Stack (most recent call first):
    /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
    cmake_modules/FindSDL2.cmake:179 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    src/vizdoom/src/CMakeLists.txt:206 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-build-ivIkqp/doom-py/doom_py/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-build-ivIkqp/doom-py/doom_py/CMakeFiles/CMakeError.log".
  
  Could not build doom-py: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/anaconda2/bin/python', '-DPYTHON_LIBRARY=/anaconda2/lib/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/anaconda2/include/python2.7']' returned non-zero exit status 1. (HINT: are you sure cmake is installed? You might also be missing a library. Try running 'apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip'
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 88, in <module>
      include_package_data=True,
    File "/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/anaconda2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 63, in run
      build_func()
    File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 41, in build_linux
      build_common('so')
    File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 28, in build_common
      subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH={}'.format(sys.executable)] + cmake_arg_list, cwd='doom_py')
    File "/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/anaconda2/bin/python', '-DPYTHON_LIBRARY=/anaconda2/lib/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/anaconda2/include/python2.7']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for doom-py
  Running setup.py clean for doom-py
Failed to build doom-py
Installing collected packages: doom-py, ppaquette-gym-doom
  Running setup.py install for doom-py ... error
    Complete output from command /anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ivIkqp/doom-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-QrroEv-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
      Unable to find the requested Boost libraries.
    
      Boost version: 1.61.0
    
      Boost include path: /usr/include
    
      Could not find the following Boost libraries:
    
              boost_filesystem
              boost_thread
              boost_system
              boost_date_time
              boost_chrono
              boost_regex
              boost_iostreams
    
      Some (but not all) of the required Boost libraries were found.  You may
      need to install these additional Boost libraries.  Alternatively, set
      BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
      to the location of Boost.
    Call Stack (most recent call first):
      CMakeLists.txt:54 (find_package)
    
    
    -- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
    -- Could NOT find GME (missing:  GME_LIBRARIES GME_INCLUDE_DIR)
    -- Using system zlib
    -- Using system jpeg library
    -- Using internal bzip2 library
    -- Using internal gme library
    -- /anaconda2/include
    -- /tmp/pip-build-ivIkqp/doom-py/doom_py/src/vizdoom/bzip2
    -- /tmp/pip-build-ivIkqp/doom-py/doom_py/src/vizdoom/lzma/C
    -- Checking for module 'gtk+-2.0'
    --   No package 'gtk+-2.0' found
    CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find SDL2 (missing: SDL2_LIBRARY)
    Call Stack (most recent call first):
      /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
      cmake_modules/FindSDL2.cmake:179 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      src/vizdoom/src/CMakeLists.txt:206 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-ivIkqp/doom-py/doom_py/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-build-ivIkqp/doom-py/doom_py/CMakeFiles/CMakeError.log".
    
    Could not build doom-py: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/anaconda2/bin/python', '-DPYTHON_LIBRARY=/anaconda2/lib/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/anaconda2/include/python2.7']' returned non-zero exit status 1. (HINT: are you sure cmake is installed? You might also be missing a library. Try running 'apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip'
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 88, in <module>
        include_package_data=True,
      File "/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/anaconda2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 63, in run
        build_func()
      File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 41, in build_linux
        build_common('so')
      File "/tmp/pip-build-ivIkqp/doom-py/setup.py", line 28, in build_common
        subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH={}'.format(sys.executable)] + cmake_arg_list, cwd='doom_py')
      File "/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/anaconda2/bin/python', '-DPYTHON_LIBRARY=/anaconda2/lib/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/anaconda2/include/python2.7']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ivIkqp/doom-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-QrroEv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ivIkqp/doom-py/

**Comment by justheuristic** [comment]
>Could NOT find SDL2 (missing: SDL2_LIBRARY)

Apparently it doesn't see SDL2, which is installed (you can check it by trying to install libsdl2)
Where exactly is SDL2 installed? Try setting SDL_LIBRARY to the appropriate path.

**Comment by juliagusak** [comment]
I've found the following

!dpkg --get-selections | grep libsdl2
libsdl2-2.0-0:amd64				install
libsdl2-dev					install
----------------------------
!dpkg -L libsdl2-2.0-0
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.0
/usr/share
/usr/share/doc
/usr/share/doc/libsdl2-2.0-0
/usr/share/doc/libsdl2-2.0-0/BUGS.txt
/usr/share/doc/libsdl2-2.0-0/CREDITS.txt
/usr/share/doc/libsdl2-2.0-0/README-SDL.txt
/usr/share/doc/libsdl2-2.0-0/README.txt
/usr/share/doc/libsdl2-2.0-0/changelog.Debian.gz
/usr/share/doc/libsdl2-2.0-0/copyright
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0

-------------------------
!dpkg -L libsdl2-dev
/usr
/usr/bin
/usr/bin/sdl2-config
/usr/include
/usr/include/SDL2
/usr/include/SDL2/SDL.h
/usr/include/SDL2/SDL_assert.h
/usr/include/SDL2/SDL_atomic.h
/usr/include/SDL2/SDL_audio.h
/usr/include/SDL2/SDL_bits.h
/usr/include/SDL2/SDL_blendmode.h
/usr/include/SDL2/SDL_clipboard.h
/usr/include/SDL2/SDL_config.h
/usr/include/SDL2/SDL_cpuinfo.h
/usr/include/SDL2/SDL_egl.h
/usr/include/SDL2/SDL_endian.h
/usr/include/SDL2/SDL_error.h
/usr/include/SDL2/SDL_events.h
/usr/include/SDL2/SDL_filesystem.h
/usr/include/SDL2/SDL_gamecontroller.h
/usr/include/SDL2/SDL_gesture.h
/usr/include/SDL2/SDL_haptic.h
/usr/include/SDL2/SDL_hints.h
/usr/include/SDL2/SDL_joystick.h
/usr/include/SDL2/SDL_keyboard.h
/usr/include/SDL2/SDL_keycode.h
/usr/include/SDL2/SDL_loadso.h
/usr/include/SDL2/SDL_log.h
/usr/include/SDL2/SDL_main.h
/usr/include/SDL2/SDL_messagebox.h
/usr/include/SDL2/SDL_mouse.h
/usr/include/SDL2/SDL_mutex.h
/usr/include/SDL2/SDL_name.h
/usr/include/SDL2/SDL_opengl.h
/usr/include/SDL2/SDL_opengl_glext.h
/usr/include/SDL2/SDL_opengles.h
/usr/include/SDL2/SDL_opengles2.h
/usr/include/SDL2/SDL_opengles2_gl2.h
/usr/include/SDL2/SDL_opengles2_gl2ext.h
/usr/include/SDL2/SDL_opengles2_gl2platform.h
/usr/include/SDL2/SDL_opengles2_khrplatform.h
/usr/include/SDL2/SDL_pixels.h
/usr/include/SDL2/SDL_platform.h
/usr/include/SDL2/SDL_power.h
/usr/include/SDL2/SDL_quit.h
/usr/include/SDL2/SDL_rect.h
/usr/include/SDL2/SDL_render.h
/usr/include/SDL2/SDL_revision.h
/usr/include/SDL2/SDL_rwops.h
/usr/include/SDL2/SDL_scancode.h
/usr/include/SDL2/SDL_shape.h
/usr/include/SDL2/SDL_stdinc.h
/usr/include/SDL2/SDL_surface.h
/usr/include/SDL2/SDL_system.h
/usr/include/SDL2/SDL_syswm.h
/usr/include/SDL2/SDL_test.h
/usr/include/SDL2/SDL_test_assert.h
/usr/include/SDL2/SDL_test_common.h
/usr/include/SDL2/SDL_test_compare.h
/usr/include/SDL2/SDL_test_crc32.h
/usr/include/SDL2/SDL_test_font.h
/usr/include/SDL2/SDL_test_fuzzer.h
/usr/include/SDL2/SDL_test_harness.h
/usr/include/SDL2/SDL_test_images.h
/usr/include/SDL2/SDL_test_log.h
/usr/include/SDL2/SDL_test_md5.h
/usr/include/SDL2/SDL_test_random.h
/usr/include/SDL2/SDL_thread.h
/usr/include/SDL2/SDL_timer.h
/usr/include/SDL2/SDL_touch.h
/usr/include/SDL2/SDL_types.h
/usr/include/SDL2/SDL_version.h
/usr/include/SDL2/SDL_video.h
/usr/include/SDL2/begin_code.h
/usr/include/SDL2/close_code.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/cmake
/usr/lib/x86_64-linux-gnu/cmake/SDL2
/usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake
/usr/lib/x86_64-linux-gnu/libSDL2.a
/usr/lib/x86_64-linux-gnu/libSDL2_test.a
/usr/lib/x86_64-linux-gnu/libSDL2main.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/sdl2.pc
/usr/share
/usr/share/aclocal
/usr/share/aclocal/sdl2.m4
/usr/share/doc
/usr/share/doc/libsdl2-dev
/usr/share/doc/libsdl2-dev/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/sdl2-config.1.gz
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2.so
/usr/share/doc/libsdl2-dev/changelog.Debian.gz

How should I change the path?
